//// EQM
export const FIND_EQM_BY_ID = 'FIND_EQM_BY_ID';
export const FETCH_LIST_EQM_SUCCESS = 'FETCH_LIST_EQM_SUCCESS';
export const FETCH_LIST_EQM_FAIL = 'FETCH_LIST_EQM_FAIL';

//CUSTOMER
export const FETCH_LIST_CUS_SUCCESS = 'FETCH_LIST_CUS_SUCCESS';
export const FETCH_LIST_CUS_FAIL = 'FETCH_LIST_CUS_FAIL';
export const FIND_CUSTOMER_BY_NAME = 'FIND_CUSTOMER_BY_NAME';

///SUPPLIER
export const FETCH_LIST_SUP_SUCCESS = 'FETCH_LIST_SUP_SUCCESS';
export const FETCH_LIST_SUP_FAIL = 'FETCH_LIST_SUP_FAIL';
export const FIND_SUPPLIER_BY_NAME = 'FIND_SUPPLIER_BY_NAME';

export const FETCH_SUP_BY_iD = 'FETCH_SUP_BY_iD';
export const POST_NEW_SUP = 'POST_NEW_SUP';
export const UPDATE_SUP = 'UPDATE_SUP';
export const DELETE_SUP = 'DELETE_SUP';

//EXport

export const FETCH_LIST_EXPORT_SUCCESS = 'FETCH_LIST_EXPORT_SUCCESS';
export const FETCH_LIST_EXPORT_FAIL = 'FETCH_LIST_EXPORT_FAIL';
export const FIND_EXPORT_BY_ID = 'FIND_EXPORT_BY_ID';

/// import

export const FETCH_LIST_IMPORT_SUCCESS = 'FETCH_LIST_IMPORT_SUCCESS';
export const FETCH_LIST_IMPORT_FAIL = 'FETCH_LIST_IMPORT_FAIL';
export const FIND_IMPORT_BY_ID = 'FIND_IMPORT_BY_ID';

//login

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

//register

export const REGISTER_FAIL = 'REGISTER_FAIL';
