//// EQM

export const FETCH_LIST_EQM_SUCCESS = 'FETCH_LIST_EQM_SUCCESS';
export const FETCH_LIST_EQM_FAIL = 'FETCH_LIST_EQM_FAIL';

export const FETCH_EQM_BY_iD = 'FETCH_EQM_BY_iD';
export const POST_NEW_EQM = 'POST_NEW_EQM';
export const UPDATE_EQM = 'UPDATE_EQM';
export const DELETE_EQM = 'DELETE_EQM';
//CUSTOMER
export const FETCH_LIST_CUS_SUCCESS = 'FETCH_LIST_CUS_SUCCESS';
export const FETCH_LIST_CUS_FAIL = 'FETCH_LIST_CUS_FAIL';

export const FETCH_CUS_BY_iD = 'FETCH_CUS_BY_iD';
export const POST_NEW_CUS = 'POST_NEW_CUS';
export const UPDATE_CUS = 'UPDATE_CUS';
export const DELETE_CUS = 'DELETE_CUS';

///SUPPLIER
export const FETCH_LIST_SUP_SUCCESS = 'FETCH_LIST_SUP_SUCCESS';
export const FETCH_LIST_SUP_FAIL = 'FETCH_LIST_SUP_FAIL';

export const FETCH_SUP_BY_iD = 'FETCH_SUP_BY_iD';
export const POST_NEW_SUP = 'POST_NEW_SUP';
export const UPDATE_SUP = 'UPDATE_SUP';
export const DELETE_SUP = 'DELETE_SUP';
