POST  http://localhost:4000/auth/register
Content-Type: application/json

{
  "username":"admin",
  "password":"11111"
}

#### 


POST  http://localhost:4000/auth/login
Content-Type: application/json

{
  "username":"admin",
  "password":"11111"
}

### Get all Eqm



GET   http://localhost:4000/equitment
Content-Type: application/json


### Post all Eqm



POST    http://localhost:4000/equitment
Content-Type: application/json


{
  "id":3333,
  "name": "Xe Cap cuu",
  "model": "NHDS",
"department":"Benh vien",
"branch":"LocalBrand",
"country":"TQuoc",
"img":"anh","description":"Vuot den xanh"

}
###

GET   http://localhost:4000/equitment/BCX
Content-Type: application/json


###

DELETE    http://localhost:4000/equitment/4239
Content-Type: application/json

###

PUT     http://localhost:4000/equitment/3931
Content-Type: application/json


{
  "id":3931,
  "name": "Xe Cap cuu 123",
  "model": "NHDS",
"department":"Benh vien XYZ ",
"branch":"LocalBrand",
"country":"TQuoc",
"img":"anh 1111",
"description":"Vuot den xanh"
}


///////////////////Cus


### Get all Cus



GET   http://localhost:4000/customer/2
Content-Type: application/json


### Post all Cus



POST    http://localhost:4000/customer
Content-Type: application/json


{
  "id":3062,
  "name": "Pham Ngoc ",
  "address":"Ha Noi",
  "phone":  "0987272867",
  "email": "NN@gmial.com",
  "age": 20,
  "gender": false
}
###

GET   http://localhost:4000/customer/416
Content-Type: application/json


###

DELETE    http://localhost:4000/customer/3060
Content-Type: application/json

###

PUT     http://localhost:4000/customer/4845
Content-Type: application/json


{
  "id":4845,
  "name": "Pham Ngoc Binh",
  "address":"Ha Noi",
  "phone":  "0987272867",
  "email": "Binh@gmial.com",
  "age": 22,
  "gender": true
}

//////////////////////////Suplier
###

GET   http://localhost:4000/supplier
Content-Type: application/json


### Post all Cus



POST    http://localhost:4000/supplier
Content-Type: application/json


{
  "id":"11113",
  "name": "Pham Ngoc Binh",
  "address":"Ha Noi",
  "phone":  "0987272867",
  "email": "Binh@gmial.com"
}
###

GET   http://localhost:4000/supplier/7060
Content-Type: application/json


###

DELETE    http://localhost:4000/supplier/7060
Content-Type: application/json

###

PUT     http://localhost:4000/supplier/7060
Content-Type: application/json


{
"id":"11113",
  "name": "Pham Ngoc Binh",
  "address":"Ha Noi",
  "phone":  "0987272867",
  "email": "Binh@gmial.com"
}


///////////////////////////////////////Export
###

GET    http://localhost:4000/export/1
Content-Type: application/json

######


GET    http://localhost:4000/export/information/58547
Content-Type: application/json

######


POST   http://localhost:4000/export
Content-Type: application/json

{
  "id":44444,
  "customerid":33333,
  "invoice":[
    {
      "exid":44444,
      "eid":"VSV",
      "amount":300,
      "price":500
    },
    {
      "exid":44444,
      "eid":"BCX",
      "amount":300,
      "price":500
    }
  ]

}
